### PR TITLE
Documentation for fulldummy

### LINKED ISSUE #255: document fulldummy
the `zerocorr*` functions are documented (in constructors.jmd) but `fulldummy` isn't.  Might be a  good idea to have a separate "formula extensions" page to document all the special syntax that mixed models introduces.

### PR DESCRIPTION
**Pull request by dmbates**
- closes #255 
- add a docstring for `fulldummy` and an example in the `constructors.md` source file for the online documentation

### CODE REVIEW

**Review by palday — COMMENTED** [review]
Looks good so far. I think one of the things @kleinschmidt has been working on is what happens when you have `(1 + fulldummy(x)|g)` vs. `(1|g)` + `(0+fulldummy(x)|g)`. Like `||`, the `lme4` behavior for `dummy()` is somewhat surprising about when the intercept is repeated and when not. I think the current implementation (#269) is consistent and nice, but I suspect edge cases will keep cropping up.

**Comment by kleinschmidt** [comment]
I think after #338 you should be able to do `(1|g) + (fulldummy(x) | g)` (without needing the `0+`).

**Comment by palday** [comment]
@kleinschmidt Yeah, that makes sense and is consistent (which is what you were going for :grin: ).

**Comment by dmbates** [comment]
I am a bit queasy about the use of the sleepstudy data to illustrate `fulldummy` and especially `zerocorr(1+fulldummy(days))`.  This is obviously longitudinal data - in fact it is a classic example of multiple, short, time series - and using indicators for the days and then declaring that the random effects could be independent is, well, questionable.  It is fine for illustrating the capabilities but its interpretation is problematic.

If anyone can suggest an alternative it would be welcome.  Right now I am just looking to close issues tagged as Release 3.

**Comment by palday** [comment]
What about `machines`?

**Comment by dmbates** [comment]
I suppose `machines` could be used.  @kliegl can you suggest models to fit?

**Comment by palday** [comment]
@kleinschmidt Since you've obsessed about gotchas in `fulldummy`: are there any major ones we should clarify? We can always improve the documentation later, but known edge cases that we've made an API decision on are something we should probably also just document for ourselves.

**Comment by kleinschmidt** [comment]
I don't know of any major gotchas but then again I'm probably the wrong person to ask :)  I think the biggest potential one is that it's going to not "play nicely" with other categorical predictors and the intercept I think...so like `(fulldummy(x) | g)` might add an intercept...or if you have `(fulldummy(x) + y | g)` then you might still get promotion of `y` to full rank, but I haven't checked that.  But those seem like a real edge case and if you're doing that then...you probably have a good reason.

**Comment by palday** [comment]
So maybe we just add a byline:

> The interaction of `fulldummy` with complex random effects is subtle and complex with numerous potential edge cases. As we discover these edge cases, we will document and determine their behavior. Until such time, please check the model summary to verify that the expansion is working as you expected. If it is not, please report a use case on GitHub.

**Comment by dmbates** [comment]
@palday Can you handle the clean-up and squash and merge on this one?

**Comment by palday** [comment]
@dmbates will do :grinning:

**Review by palday — APPROVED** [review]

**Pull request merged**
