### PR TITLE
More sophisticated checks in restoreoptsum.

### LINKED ISSUE #774: restoreoptsum fails after change in JSON file structure in 4.25.0
One of the first checks in `restoreoptsum` is on the keys in the dictionary created from the JSON file.  If the optsum JSON file was created with a version prior to 4.25 attempts to restore this optsum under 4.25.0 will fail, with a somewhat misleading error message.  I will split the checks into two parts, one on the fields and one on the lower bounds and allow for patching pre-4.25 saved optsums to the 4.25 names.

### PR DESCRIPTION
**Pull request by dmbates**
Closes #774

Did behavior change? Did you add need features? If so, please update NEWS.md
- [x] add entry in NEWS.md
- [x] after opening this PR, add a reference and run `docs/NEWS-update.jl` to update the cross-references.

Should we release your changes right away? If so, bump the version:
- [x] I've bumped the version appropriately

### CODE REVIEW

**Comment by palday** [comment]
@dmbates can you add a test with loading a 4.22 optsum? That would also serve as a potential test if we add even more fields (`restoreoptsum!` would break again and thus we would be reminded to update it).

**Comment by dmbates** [comment]
I added tests and improved coverage slightly.

**Comment by palday** [comment]
@dmbates I made a few changes directly:

- made sure that "optional" fields are actually loaded when they exist
- (fixed an old bug in how that was done for `fitlog`)
- issue a warning when loading an old fit

**Review by palday — APPROVED** [review]

**Comment by dmbates** [comment]
Did I accidentally commit a `lcov.info` file?  I use the "Run tests with coverage" option in VS code which creates a `lcov.info` file and I see you have added that name to `.gitignore`

**Comment by palday** [comment]
> Did I accidentally commit a `lcov.info` file? I use the "Run tests with coverage" option in VS code which creates a `lcov.info` file and I see you have added that name to `.gitignore`

No, but I almost did :joy:

**Comment by dmbates** [comment]
@JuliaRegistrator register

**Pull request merged**
