### PR TITLE
link to l

### PR DESCRIPTION
**Pull request by yakir12**

### CODE REVIEW

**Comment by yakir12** [comment]
While this looks good, I am getting these errors from trying this:
```julia
julia> fm = fit!(GeneralizedLinearMixedModel(@formula(homebound ~ 1 + Run + (1+Run|Id)), df, Normal(), SqrtLink()))
ERROR: ArgumentError: invalid NLopt arguments: zero step size
Stacktrace:
 [1] chk(::NLopt.Opt, ::NLopt.Result) at /home/yakir/.julia/packages/NLopt/eqN9a/src/NLopt.jl:237
 [2] initial_step! at /home/yakir/.julia/packages/NLopt/eqN9a/src/NLopt.jl:340 [inlined]
 [3] NLopt.Opt(::OptSummary{Float64}) at /home/yakir/.julia/packages/MixedModels/eXZQr/src/optsummary.jl:85
 [4] #fit!#59(::Bool, ::Bool, ::Int64, ::typeof(fit!), ::GeneralizedLinearMixedModel{Float64}) at /home/yakir/.julia/packages/MixedModels/eXZQr/src/generalizedlinearmixedmodel.jl:182
 [5] fit!(::GeneralizedLinearMixedModel{Float64}) at /home/yakir/.julia/packages/MixedModels/eXZQr/src/generalizedlinearmixedmodel.jl:160
 [6] top-level scope at REPL[9]:1
```

Maybe specifying a non identity link function is simply not cosher?

**Comment by palday** [comment]
See #94, #95 .

**Comment by palday** [comment]
The fix for the NLopt error (#201) hasn't landed yet because the test case we have for that depends on the gamma functionality. If we had a good test case that didn't depend on that, I would split the PR and go ahead and get the boundary fit issue in.

**Comment by yakir12** [comment]
> If we had a good test case that didn't depend on that, I would split the PR and go ahead and get the boundary fit issue in.

Can I help with that? I have data that isn't gamma related...

**Comment by palday** [comment]
Yes, please. Esp if it's a small dataset (both for repository and speed-of-tests reasons).

**Comment by yakir12** [comment]
I am unsure exactly what this would entail, but here is the CSV for the tiny data-set:
https://s3.eu-central-1.amazonaws.com/vision-group-file-sharing/Data backup and storage/Yakir/coffee beetles/beetles.csv
Not sure what else you need. I can give a short explanation, or the code to test it, let me know...

**Comment by palday** [comment]
The code to fit the model (so formula, family, link).

**Comment by yakir12** [comment]
A "simple" case:
```julia
using CSV, DataFrames, MixedModels
df = CSV.File("beetles.csv") |> DataFrame
df = df[!, Not(:outbound)]
fm = fit!(GeneralizedLinearMixedModel(@formula(homebound ~ 1 + Run + (1+Run|Id)), df, Normal(), LogLink()))
```
and more complicated:
```julia
df = CSV.File("beetles.csv") |> DataFrame
df = stack(df, variable_name = :Direction, value_name = :Speed)
fm = fit!(GeneralizedLinearMixedModel(@formula(Speed ~ 1 + Run * Direction + (1 + Run |Id)), df, Normal(), LogLink()))
```

**Comment by dmbates** [comment]
I think we should merge this change (it corrects an obvious error) and move the discussions to #94 and #95

**Pull request merged**
