### PR TITLE
NEWS update for 545

### PR DESCRIPTION
**Pull request by palday**
@dmbates actually, while I've paused releasing 4.1, should we add a `ranef(model, fname)` method to complement the `condVar` method?

### CODE REVIEW

**Review by dmbates — COMMENTED** [review]
Seems like a good idea to create a `ranef(m, :gf)` method.  Let me take a look and get back to you in the discussion of this PR.  (And thanks for adding the update to `NEWS.md` which I always forget to do.)

**Review by dmbates — APPROVED** [review]
I think that writing a `ranef(m, :gf)` method is a bit more than I want to take on right now.  It is just finicky enough that it would start to be a time sink.  I should probably concentrate on notebooks at this time.

**Comment by palday** [comment]
>  I think that writing a `ranef(m, :gf)` method is a bit more than I want to take on right now. It is just finicky enough that it would start to be a time sink.

That's exactly why I didn't just do it myself. :smile:

**Comment by kliegl** [comment]
> @dmbates actually, while I've paused releasing 4.1, should we add a `ranef(model, fname)` method to complement the `condVar` method?

I will check it out. Thanks so much!

**Pull request merged**
