### PR TITLE
Initial version of NEWS

### PR DESCRIPTION
**Pull request by dmbates**
- Initial version of `NEWS.md` and script to add footnotes for commit numbers

### CODE REVIEW

**Comment by dmbates** [comment]
The ordering of the sections is from the order in which I encountered the changes.  I think it should be in terms of importance which I would suggest is
- ReMat and FeMat types
- New formula features
- Rank deficiency
- Principal components
- Parametric bootstrap
- Availability of test data sets
- Replacement capabilities
- Package dependencies

How does that look?  Alternatives are welcome.

The purpose of the NEWS-update.jl file is to be run before the branch release to add URLs for issue numbers.  It was blatantly stolen from the Julia repository.

**Comment by palday** [comment]
I'm torn about the position of Re- and FeMat. On the one hand, those are important changes, but on the other hand, it's mostly our close collaborators, who are developing functionality based on those, that care. 

The rest of the ordering looks great.

**Comment by dmbates** [comment]
Okay, I agree with what you said.  How about moving `ReMat and FeMat types` to just before `Availability of test data sets`?

**Comment by palday** [comment]
@dmbates Works for me!

**Comment by dmbates** [comment]
Should I make these changes or will you?  Either is okay with me.

**Review by palday — APPROVED** [review]

**Comment by palday** [comment]
Looks good to me now!

**Pull request merged**
