### PR TITLE
Bump compatibility for Tables; patch version bump

### PR DESCRIPTION
**Pull request by palday**
If everybody is happy with this, then call JuliaRegistrator on the relevant commit. After TagBot has done it's job, close the PR without merging and delete the branch.  The tag will keep the relevant commit from being garbage collected by git.

### CODE REVIEW

**Comment by palday** [comment]
@Nosferican Do you want to have the honor of making the release?

**Comment by palday** [comment]
Yes.

**Comment by palday** [comment]
Finally got to use `git cherry-pick`.

**Comment by palday** [comment]
So bringing in those changes cuts Julia 1.2 support -- is that too much for a patch release?

**Comment by palday** [comment]
In other words, should this move from a patch to a minor release?

**Comment by dmbates** [comment]
Yes, minor release I think.

**Comment by Nosferican** [comment]
What exactly cuts the support for Julia v1.2?

**Comment by palday** [comment]
The `mul!` methods -- these got pulled in with cherry-pick to support newer Distributions (which required newer BlockArrays).

**Comment by dmbates** [comment]
@JuliaRegistrator register()

**Pull request closed without merging**
