### PR TITLE
Fix the docs build and deployment

### PR DESCRIPTION
**Pull request by DilumAluthge**
This should fix the docs build and deployment.

Once this is merged, the dev docs will be built and deployed based on `master`.

To build and deploy the docs for previous releases that may have failed to have docs, see the "Fixing broken release deployments" section of [this page](https://juliadocs.github.io/Documenter.jl/stable/man/hosting/).

The key part of this PR is that you need a separate "Documentation" job in your GitHub Actions workflow. This is not necessarily intuitive. Personally, I always use PkgTemplates to generate these files for me. (Actually, that's what I did for this PR - I used PkgTemplates to generate a package named "MixedModels", then I just copied the workflow files it generated.)
https://github.com/JuliaStats/MixedModels.jl/blob/03257aa8841e244b0ad68095e652040d6676a293/.github/workflows/ci.yml#L55-L56

cc: @ararslan @palday @dmbates

### CODE REVIEW

**Comment by palday** [comment]
Thanks @DilumAluthge  -- it looks like what I was doing in #423 was the right thing. :)

**Comment by DilumAluthge** [comment]
@palday It looks like MixedModels.jl has one or more failing doctests.

I will comment out the doctests section for now. Once you have fixed the doctests, you can uncomment that section.

**Comment by DilumAluthge** [comment]
Closing in favor of #423

**Comment by palday** [comment]
Thanks for helping @DilumAluthge -- some things from this made it into #423. :smile:

**Pull request closed without merging**
